modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved."
issueTrackerURL="https://github.com/FireController1847/ModTesting/issues"

[[mods]]
    modId="modtesting"
    version="1.0.0-SNAPSHOT"
    displayName="ModTesting"
    authors="FireControl1847"
    description="Mod. Testing. MOD. TESTING. M O D. T E S T I N G. M O D! T E S T I N G!"

[[dependencies.modtesting]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"